from __future__ import annotations

import asyncio
import logging
from datetime import UTC, datetime, timedelta
from pathlib import Path

from celery import Celery
from sqlalchemy import func, select
from sqlalchemy.exc import OperationalError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from .config import get_settings
from .database import TaskSessionLocal
from .events import publish_media_event, publish_post_event, publish_realtime_event
from .media import create_thumbnail, probe_video, sha256_file
from .models import (
    AIGenerationJob,
    BillingEvent,
    MediaAsset,
    Post,
    Publication,
    PublicationAttempt,
    Subscription,
    User,
    utcnow,
)
from .notifications import deliver_pending_notifications, queue_terminal_notification
from .providers import (
    ProviderError,
    UploadPostClient,
    upload_idempotency_key,
    upload_request_id,
)
from .storage import R2Storage, StorageError, materialize_object

settings = get_settings()
UNCLAIMED_QUEUE_TIMEOUT = timedelta(minutes=1)
CLAIMED_QUEUE_TIMEOUT = timedelta(minutes=15)
MAX_SUBMISSION_ATTEMPTS = 4
logger = logging.getLogger(__name__)
celery_app = Celery("marble", broker=settings.redis_url, backend=settings.redis_url)
celery_app.conf.update(
    task_acks_late=True,
    task_reject_on_worker_lost=True,
    broker_connection_retry_on_startup=True,
    beat_schedule={
        "reconcile-active-posts": {"task": "marble.reconcile_active", "schedule": 10.0},
        "cleanup-expired-media": {"task": "marble.cleanup_media", "schedule": 3600.0},
        "deliver-post-notifications": {
            "task": "marble.deliver_post_notifications",
            "schedule": 30.0,
        },
        "process-billing-events": {"task": "marble.process_pending_billing_events", "schedule": 30.0},
        "sync-due-analytics": {"task": "marble.sync_due_analytics", "schedule": 86400.0},
        "enforce-expired-access": {"task": "marble.enforce_expired_access", "schedule": 3600.0},
    },
)


def filename_derived_title(title: str | None, filename: str) -> bool:
    """Identify titles generated by the old filename-based YouTube fallback."""
    if not title:
        return False
    generated_title = Path(filename).stem.replace("-", " ").replace("_", " ").strip()
    return bool(generated_title) and title.strip().casefold() == generated_title.casefold()


async def _process_media(media_id: str) -> None:
    async with TaskSessionLocal() as db:
        asset = await db.get(MediaAsset, media_id)
        if not asset or asset.status not in {"processing", "uploaded"}:
            return
        asset.status = "processing"
        await db.commit()

        try:
            if asset.storage_backend == "r2":
                if not asset.object_key:
                    raise ValueError("The uploaded video is no longer available")
                storage = R2Storage(settings)
                async with materialize_object(
                    storage_backend=asset.storage_backend,
                    object_key=asset.object_key,
                    storage_path=asset.storage_path,
                    filename=asset.original_name,
                ) as video_path:
                    thumbnail = video_path.parent / f"{asset.id}.jpg"
                    checksum = await asyncio.to_thread(sha256_file, video_path)
                    duration, width, height = await asyncio.to_thread(probe_video, video_path)
                    if duration < 1 or duration > 600:
                        raise ValueError("Videos must be between 1 second and 10 minutes")
                    await asyncio.to_thread(create_thumbnail, video_path, thumbnail)
                    thumbnail_key = asset.thumbnail_key or storage.thumbnail_key(asset.user_id, asset.id)
                    await storage.put_file(thumbnail, thumbnail_key, "image/jpeg")
            else:
                video_path = Path(asset.storage_path)
                checksum = await asyncio.to_thread(sha256_file, video_path)
                duration, width, height = await asyncio.to_thread(probe_video, video_path)
                if duration < 1 or duration > 600:
                    raise ValueError("Videos must be between 1 second and 10 minutes")
                thumbnail = settings.storage_root / "thumbnails" / f"{asset.id}.jpg"
                await asyncio.to_thread(create_thumbnail, video_path, thumbnail)
                thumbnail_key = None
        except StorageError:
            # Preserve the processing state so Celery can safely retry the same
            # idempotent validation job.
            raise
        except (RuntimeError, ValueError, KeyError, OSError) as exc:
            current = await db.get(MediaAsset, media_id)
            if current:
                current.status = "failed"
                current.delete_after = datetime.now(UTC) + timedelta(days=7)
                await db.commit()
                await publish_media_event(current.user_id, current.id)
            logger.info("Media validation failed for %s: %s", media_id, exc)
            return

        current = await db.get(MediaAsset, media_id)
        if not current or current.status not in {"processing", "uploaded"}:
            return
        current.checksum_sha256 = checksum
        current.duration_seconds = duration
        current.width = width
        current.height = height
        if current.storage_backend == "r2":
            current.thumbnail_key = thumbnail_key
        else:
            current.thumbnail_path = str(thumbnail)
        current.status = "ready"
        current.delete_after = datetime.now(UTC) + timedelta(days=7)
        await db.commit()
        await publish_media_event(current.user_id, current.id)


async def _fail_media_processing(media_id: str) -> None:
    async with TaskSessionLocal() as db:
        asset = await db.get(MediaAsset, media_id)
        if not asset or asset.status != "processing":
            return
        asset.status = "failed"
        asset.delete_after = datetime.now(UTC) + timedelta(days=7)
        await db.commit()
        await publish_media_event(asset.user_id, asset.id)


@celery_app.task(bind=True, name="marble.process_media", max_retries=3)
def process_media(task, media_id: str) -> None:
    try:
        asyncio.run(_process_media(media_id))
    except (StorageError, OperationalError) as exc:
        if task.request.retries >= task.max_retries:
            asyncio.run(_fail_media_processing(media_id))
            return
        raise task.retry(exc=exc, countdown=2 ** task.request.retries) from exc


def derive_post_status(post: Post) -> str:
    statuses = [item.status for item in post.publications]
    if not statuses:
        return post.status
    if all(status == "scheduled" for status in statuses):
        return "scheduled"
    if any(status in {"scheduled", "queued", "publishing"} for status in statuses):
        return "publishing"
    if all(status == "published" for status in statuses):
        return "published"
    if all(status in {"failed", "action_required"} for status in statuses):
        return "failed"
    return "partially_published"


def post_state_signature(post: Post) -> tuple:
    return (
        post.status,
        post.provider_request_id,
        post.provider_job_id,
        tuple(
            sorted(
                (
                    item.platform,
                    item.status,
                    item.url,
                    item.error_code,
                    item.error_message,
                    item.fallback_to_inbox,
                )
                for item in post.publications
            )
        ),
    )


def mark_connections_used(post: Post, platforms: set[str]) -> None:
    used_at = utcnow()
    for connection in post.user.connections:
        if connection.platform in platforms:
            connection.last_used_at = used_at


def provider_result_status(result: dict) -> str:
    if result.get("fallback_to_inbox"):
        return "action_required"
    raw = str(result.get("status", "")).lower()
    message = str(result.get("message", "")).lower()
    if raw == "completed":
        return "published"
    # Upload-Post can report success=false while a platform result is
    # retryable. That state is non-terminal: the provider may still complete
    # the original request, so exposing a retry here can create a duplicate.
    if raw in {"processing", "in_progress", "retryable"}:
        return "publishing"
    if raw in {"pending", "queued"}:
        return "queued"
    if result.get("skipped") or raw == "failed" or result.get("success") is False:
        return "failed"
    # Some status responses use success=true to mean that the platform job was
    # accepted, while their message still says it is queued or processing.
    if result.get("success") is True:
        if "queue" in message or "pending" in message:
            return "queued"
        if "processing" in message or "progress" in message:
            return "publishing"
        return "published"
    return "queued"


def normalized_results(payload: dict) -> list[dict]:
    single_result = payload.get("result")
    if isinstance(single_result, dict) and payload.get("platform"):
        return [{"platform": payload["platform"], **single_result}]
    results = payload.get("results") or []
    if isinstance(results, dict):
        return [
            {"platform": platform, **(value if isinstance(value, dict) else {})}
            for platform, value in results.items()
        ]
    return [value for value in results if isinstance(value, dict)]


async def apply_provider_payload(post: Post, payload: dict) -> None:
    previously_published = {
        item.platform for item in post.publications if item.status == "published"
    }
    source_request_id = payload.get("request_id")
    source_job_id = payload.get("job_id")
    by_platform = {item.platform: item for item in post.publications}
    for result in normalized_results(payload):
        platform = result.get("platform")
        publication = by_platform.get(platform)
        if not publication:
            continue
        next_status = provider_result_status(result)
        source_is_current = (
            (not source_request_id or publication.provider_request_id == source_request_id)
            and (not source_job_id or publication.provider_job_id == source_job_id)
        )
        # A late callback from an older attempt may confirm success, but it must
        # never demote a newer attempt or a post that is already live.
        if next_status != "published" and (
            publication.status == "published" or not source_is_current
        ):
            continue
        publication.status = next_status
        if next_status == "published":
            if source_request_id:
                publication.provider_request_id = source_request_id
            if source_job_id:
                publication.provider_job_id = source_job_id
        publication.url = result.get("url") or result.get("post_url") or publication.url
        publication.provider_post_id = (
            str(result.get("post_id") or result.get("video_id") or result.get("publish_id") or "") or None
        )
        publication.error_code = result.get("error_code") or result.get("skip_reason")
        publication.error_message = (
            (result.get("error") or result.get("message"))
            if publication.status == "failed"
            else None
        )
        publication.fallback_to_inbox = bool(result.get("fallback_to_inbox"))
        if publication.status == "published" and publication.published_at is None:
            publication.published_at = utcnow()
    post.status = derive_post_status(post)
    if post.status == "published":
        post.media.delete_after = utcnow() + timedelta(hours=24)
    elif post.status in {"failed", "partially_published"}:
        post.media.delete_after = utcnow() + timedelta(days=7)
    newly_published = {
        item.platform for item in post.publications if item.status == "published"
    } - previously_published
    if newly_published and settings.environment.lower() != "test":
        for countdown in (3600, 21600, 86400):
            sync_analytics.apply_async(args=[post.user_id, True], countdown=countdown)


async def record_provider_attempt(
    db: AsyncSession,
    publication: Publication,
    *,
    kind: str,
    request_id: str | None,
    job_id: str | None,
    idempotency_key: str,
    status: str,
) -> None:
    existing = await db.scalar(
        select(PublicationAttempt).where(
            PublicationAttempt.publication_id == publication.id,
            PublicationAttempt.idempotency_key == idempotency_key,
        )
    )
    if existing:
        existing.provider_request_id = request_id or existing.provider_request_id
        existing.provider_job_id = job_id or existing.provider_job_id
        existing.status = status
        return
    db.add(
        PublicationAttempt(
            publication_id=publication.id,
            kind=kind,
            status=status,
            provider_request_id=request_id,
            provider_job_id=job_id,
            idempotency_key=idempotency_key,
        )
    )


async def _publish_post(post_id: str) -> None:
    async with TaskSessionLocal() as db:
        post = await db.scalar(
            select(Post)
            .where(Post.id == post_id)
            .options(
                selectinload(Post.user).selectinload(User.connections),
                selectinload(Post.media),
                selectinload(Post.versions),
                selectinload(Post.publications),
            )
            .with_for_update()
        )
        if not post or post.status not in {"queued", "scheduled", "publishing"}:
            return
        if post.provider_request_id or post.provider_job_id:
            return
        for publication in post.publications:
            publication.status = "scheduled" if post.publish_mode == "scheduled" else "queued"
            publication.attempts += 1
        post.updated_at = utcnow()
        await db.commit()

        facebook_page_id = (
            next((item.target_page_id for item in post.user.connections if item.platform == "facebook"), None)
            if post.user.connections
            else None
        )
        expected_request_id = upload_request_id(post.id, post.schedule_revision)
        idempotency_key = upload_idempotency_key(post.id, post.schedule_revision)
        try:
            youtube_version = next(
                (item for item in post.versions if item.platform == "youtube"), None
            )
            if youtube_version and filename_derived_title(
                youtube_version.title, post.media.original_name
            ):
                raise ProviderError(
                    "youtube_title_required",
                    "Set a YouTube title before publishing",
                    422,
                )
            async with materialize_object(
                storage_backend=post.media.storage_backend,
                object_key=post.media.object_key,
                storage_path=post.media.storage_path,
                filename=post.media.original_name,
            ) as video_path:
                response = await UploadPostClient().publish_video(
                    profile=post.user.upload_post_profile,
                    video_path=video_path,
                    post_id=post.id,
                    revision=post.schedule_revision,
                    versions=[
                        {
                            "platform": item.platform,
                            "caption": item.caption,
                            "title": item.title,
                            "options": item.options,
                        }
                        for item in post.versions
                    ],
                    scheduled_at=post.scheduled_at_utc.isoformat() if post.scheduled_at_utc else None,
                    timezone=post.schedule_timezone,
                    facebook_page_id=facebook_page_id,
                    request_id=expected_request_id,
                )
            post.provider_request_id = response.get("request_id") or expected_request_id
            post.provider_job_id = response.get("job_id")
            if post.publish_mode == "scheduled" and not post.provider_job_id:
                raise ProviderError(
                    "provider_invalid_response",
                    "Upload-Post did not return a scheduled job ID",
                )
            for publication in post.publications:
                publication.provider_request_id = post.provider_request_id
                publication.provider_job_id = post.provider_job_id
                await record_provider_attempt(
                    db,
                    publication,
                    kind="initial",
                    request_id=post.provider_request_id,
                    job_id=post.provider_job_id,
                    idempotency_key=idempotency_key,
                    status="submitted",
                )
            mark_connections_used(post, {version.platform for version in post.versions})
            if post.publish_mode == "scheduled":
                post.status = "scheduled"
                post.media.delete_after = None
            else:
                post.status = "publishing"
                await apply_provider_payload(post, response)
            await queue_terminal_notification(db, post)
            await db.commit()
            await publish_post_event(post.user_id, post.id)
        except ProviderError as exc:
            post.provider_request_id = expected_request_id
            for publication in post.publications:
                publication.provider_request_id = expected_request_id
                publication.status = "failed"
                publication.error_code = exc.code
                publication.error_message = str(exc)
                await record_provider_attempt(
                    db,
                    publication,
                    kind="initial",
                    request_id=expected_request_id,
                    job_id=None,
                    idempotency_key=idempotency_key,
                    status="unknown" if exc.code == "provider_unavailable" else "failed",
                )
            post.status = "draft" if post.publish_mode == "scheduled" else "failed"
            post.media.delete_after = utcnow() + timedelta(days=7)
            await queue_terminal_notification(db, post)
            await db.commit()
            await publish_post_event(post.user_id, post.id)


@celery_app.task(
    name="marble.publish_post",
    autoretry_for=(OSError, OperationalError),
    retry_backoff=True,
    max_retries=3,
)
def publish_post(post_id: str) -> None:
    asyncio.run(_publish_post(post_id))


async def _reconcile_post(post_id: str) -> None:
    async with TaskSessionLocal() as db:
        post = await db.scalar(
            select(Post)
            .where(Post.id == post_id)
            .options(selectinload(Post.media), selectinload(Post.publications))
        )
        if not post or not (post.provider_request_id or post.provider_job_id):
            return
        before = post_state_signature(post)
        try:
            payload = await UploadPostClient().status(
                request_id=post.provider_request_id, job_id=post.provider_job_id
            )
        except ProviderError:
            return
        await apply_provider_payload(post, payload)
        individual = {
            item.provider_request_id
            for item in post.publications
            if item.provider_request_id and item.provider_request_id != post.provider_request_id
        }
        for request_id in individual:
            try:
                retry_payload = await UploadPostClient().status(request_id=request_id)
            except ProviderError:
                continue
            await apply_provider_payload(post, retry_payload)
        await queue_terminal_notification(db, post)
        await db.commit()
        if post_state_signature(post) != before:
            await publish_post_event(post.user_id, post.id)


@celery_app.task(name="marble.reconcile_post")
def reconcile_post(post_id: str) -> None:
    asyncio.run(_reconcile_post(post_id))


async def _retry_platform(post_id: str, platform: str) -> None:
    async with TaskSessionLocal() as db:
        post = await db.scalar(
            select(Post)
            .where(Post.id == post_id)
            .options(
                selectinload(Post.user).selectinload(User.connections),
                selectinload(Post.media),
                selectinload(Post.versions),
                selectinload(Post.publications),
            )
        )
        if not post:
            return
        publication = next((item for item in post.publications if item.platform == platform), None)
        version = next((item for item in post.versions if item.platform == platform), None)
        if not publication or not version or publication.status != "queued":
            return
        client = UploadPostClient()
        original_request_id = publication.provider_request_id or post.provider_request_id
        original_job_id = publication.provider_job_id or post.provider_job_id
        provider_confirmed_missing = False

        # A local failure can be a false negative. Always ask the provider what
        # happened before creating any new social post.
        if original_request_id or original_job_id:
            try:
                status_payload = await client.status(
                    request_id=original_request_id, job_id=original_job_id
                )
            except ProviderError as exc:
                if exc.status_code == 404:
                    provider_confirmed_missing = True
                else:
                    publication.status = "failed"
                    publication.error_code = "retry_status_unavailable"
                    publication.error_message = (
                        "Could not verify the original post, so Reverb did not risk posting it twice"
                    )
                    post.status = derive_post_status(post)
                    await queue_terminal_notification(db, post)
                    await db.commit()
                    await publish_post_event(post.user_id, post.id)
                    return
            else:
                await apply_provider_payload(post, status_payload)
                target_result = next(
                    (
                        result
                        for result in normalized_results(status_payload)
                        if result.get("platform") == platform
                    ),
                    None,
                )
                target_status = (
                    provider_result_status(target_result)
                    if target_result
                    else str(status_payload.get("status", "")).lower()
                )
                if target_status == "completed":
                    target_status = "published"
                elif target_status in {"pending", "queued"}:
                    target_status = "queued"
                elif target_status in {"processing", "in_progress"}:
                    target_status = "publishing"
                if target_status == "published" or publication.status == "published":
                    publication.status = "published"
                    publication.error_code = publication.error_message = None
                    post.status = derive_post_status(post)
                    await queue_terminal_notification(db, post)
                    await db.commit()
                    await publish_post_event(post.user_id, post.id)
                    return
                if target_status in {"queued", "publishing"}:
                    publication.status = target_status
                    publication.error_code = publication.error_message = None
                    post.status = derive_post_status(post)
                    await queue_terminal_notification(db, post)
                    await db.commit()
                    await publish_post_event(post.user_id, post.id)
                    return

                failed_siblings = [
                    item
                    for item in post.publications
                    if item.status in {"failed", "action_required"}
                    and (
                        (original_request_id and item.provider_request_id == original_request_id)
                        or (original_job_id and item.provider_job_id == original_job_id)
                    )
                ]
                if target_status in {"failed", "action_required"} and len(
                    failed_siblings
                ) <= 1:
                    retry_key = (
                        f"marble-provider-retry:{post.id}:{platform}:{post.schedule_revision}"
                    )
                    try:
                        await client.retry(
                            request_id=original_request_id,
                            job_id=original_job_id,
                            idempotency_key=retry_key,
                        )
                    except ProviderError as exc:
                        publication.status = "failed"
                        publication.error_code = exc.code
                        publication.error_message = str(exc)
                    else:
                        publication.status = "queued"
                        publication.error_code = publication.error_message = None
                        publication.attempts += 1
                        mark_connections_used(post, {platform})
                        await record_provider_attempt(
                            db,
                            publication,
                            kind="provider_retry",
                            request_id=original_request_id,
                            job_id=original_job_id,
                            idempotency_key=retry_key,
                            status="submitted",
                        )
                    post.status = derive_post_status(post)
                    await queue_terminal_notification(db, post)
                    await db.commit()
                    await publish_post_event(post.user_id, post.id)
                    return

        # Legacy attempts without a provider reference, confirmed-missing
        # attempts, and a selected destination among multiple failures need a
        # platform-only request. This happens only after reconciliation above.
        publication.status = "publishing"
        publication.attempts += 1
        retry_post_id = f"{post.id}:{platform}:retry"
        expected_request_id = upload_request_id(retry_post_id, post.schedule_revision)
        retry_key = upload_idempotency_key(retry_post_id, post.schedule_revision)
        publication.provider_request_id = expected_request_id
        publication.provider_job_id = None
        await db.commit()
        await publish_post_event(post.user_id, post.id)
        facebook_page_id = next(
            (item.target_page_id for item in post.user.connections if item.platform == "facebook"), None
        )
        try:
            if platform == "youtube" and filename_derived_title(
                version.title, post.media.original_name
            ):
                raise ProviderError(
                    "youtube_title_required",
                    "Set a YouTube title before retrying",
                    422,
                )
            async with materialize_object(
                storage_backend=post.media.storage_backend,
                object_key=post.media.object_key,
                storage_path=post.media.storage_path,
                filename=post.media.original_name,
            ) as video_path:
                payload = await client.publish_video(
                    profile=post.user.upload_post_profile,
                    video_path=video_path,
                    post_id=retry_post_id,
                    revision=post.schedule_revision,
                    versions=[
                        {
                            "platform": version.platform,
                            "caption": version.caption,
                            "title": version.title,
                            "options": version.options,
                        }
                    ],
                    scheduled_at=None,
                    timezone=None,
                    facebook_page_id=facebook_page_id,
                    request_id=expected_request_id,
                )
            publication.provider_request_id = payload.get("request_id") or expected_request_id
            mark_connections_used(post, {platform})
            await record_provider_attempt(
                db,
                publication,
                kind="targeted_retry" if not provider_confirmed_missing else "missing_retry",
                request_id=publication.provider_request_id,
                job_id=None,
                idempotency_key=retry_key,
                status="submitted",
            )
            await apply_provider_payload(post, payload)
            if publication.provider_request_id and publication.status not in {
                "published",
                "failed",
                "action_required",
            }:
                publication.status = "queued"
        except StorageError as exc:
            publication.status = "queued"
            publication.error_code = "storage_unavailable"
            publication.error_message = "The video could not be retrieved for retry"
            post.status = derive_post_status(post)
            await db.commit()
            await publish_post_event(post.user_id, post.id)
            raise exc
        except ProviderError as exc:
            publication.status = "failed"
            publication.error_code = exc.code
            publication.error_message = str(exc)
            await record_provider_attempt(
                db,
                publication,
                kind="targeted_retry" if not provider_confirmed_missing else "missing_retry",
                request_id=expected_request_id,
                job_id=None,
                idempotency_key=retry_key,
                status="unknown" if exc.code == "provider_unavailable" else "failed",
            )
        post.status = derive_post_status(post)
        await queue_terminal_notification(db, post)
        await db.commit()
        await publish_post_event(post.user_id, post.id)


async def _fail_platform_retry(post_id: str, platform: str) -> None:
    async with TaskSessionLocal() as db:
        post = await db.scalar(
            select(Post)
            .where(Post.id == post_id)
            .options(selectinload(Post.publications), selectinload(Post.media))
        )
        if not post:
            return
        publication = next((item for item in post.publications if item.platform == platform), None)
        if not publication or publication.status != "queued":
            return
        publication.status = "failed"
        publication.error_code = "storage_unavailable"
        publication.error_message = "Reverb could not retrieve the video after several attempts"
        post.status = derive_post_status(post)
        post.media.delete_after = utcnow() + timedelta(days=7)
        await queue_terminal_notification(db, post)
        await db.commit()
        await publish_post_event(post.user_id, post.id)


@celery_app.task(bind=True, name="marble.retry_platform", max_retries=3)
def retry_platform(task, post_id: str, platform: str) -> None:
    try:
        asyncio.run(_retry_platform(post_id, platform))
    except (StorageError, OperationalError) as exc:
        if task.request.retries >= task.max_retries:
            asyncio.run(_fail_platform_retry(post_id, platform))
            return
        raise task.retry(exc=exc, countdown=2 ** task.request.retries) from exc


async def _reconcile_active() -> None:
    now = utcnow()
    async with TaskSessionLocal() as db:
        posts = list(
            await db.scalars(
                select(Post)
                .where(Post.status.in_(["scheduled", "publishing", "queued"]))
                .options(selectinload(Post.media), selectinload(Post.publications))
            )
        )
        reconcile_ids: list[str] = []
        redispatch_ids: list[str] = []
        failed_posts: list[tuple[str, str]] = []
        for post in posts:
            if post.provider_request_id or post.provider_job_id:
                reconcile_ids.append(post.id)
                continue
            attempts = max((item.attempts for item in post.publications), default=0)
            timeout = CLAIMED_QUEUE_TIMEOUT if attempts else UNCLAIMED_QUEUE_TIMEOUT
            updated_at = post.updated_at
            if updated_at.tzinfo is None:
                updated_at = updated_at.replace(tzinfo=UTC)
            if updated_at <= now - timeout:
                if attempts >= MAX_SUBMISSION_ATTEMPTS:
                    for publication in post.publications:
                        if publication.status not in {"published", "failed", "action_required"}:
                            publication.status = "failed"
                            publication.error_code = "submission_worker_failed"
                            publication.error_message = (
                                "Reverb could not hand this post to the publishing provider after several attempts"
                            )
                    post.status = derive_post_status(post)
                    post.media.delete_after = now + timedelta(days=7)
                    await queue_terminal_notification(db, post)
                    failed_posts.append((post.user_id, post.id))
                    continue
                # Advancing updated_at acts as a dispatch lease so the beat job
                # cannot flood Redis while this recovery attempt is waiting.
                post.updated_at = now
                redispatch_ids.append(post.id)
        await db.commit()
    for post_id in reconcile_ids:
        reconcile_post.delay(post_id)
    for post_id in redispatch_ids:
        logger.warning("Redispatching stale provider submission for post %s", post_id)
        publish_post.delay(post_id)
    for user_id, post_id in failed_posts:
        await publish_post_event(user_id, post_id)


@celery_app.task(name="marble.reconcile_active")
def reconcile_active() -> None:
    asyncio.run(_reconcile_active())


async def _deliver_post_notifications() -> None:
    async with TaskSessionLocal() as db:
        await deliver_pending_notifications(db)


@celery_app.task(
    name="marble.deliver_post_notifications",
    autoretry_for=(OSError, OperationalError),
    retry_backoff=True,
    max_retries=3,
)
def deliver_post_notifications() -> None:
    asyncio.run(_deliver_post_notifications())


async def _cleanup_media() -> None:
    async with TaskSessionLocal() as db:
        assets = list(
            await db.scalars(
                select(MediaAsset).where(
                    MediaAsset.delete_after.is_not(None), MediaAsset.delete_after <= datetime.now(UTC)
                )
            )
        )
        for asset in assets:
            post_count = await db.scalar(select(func.count(Post.id)).where(Post.media_id == asset.id))
            try:
                if asset.storage_backend == "r2":
                    storage = R2Storage()
                    if asset.multipart_upload_id and asset.object_key:
                        await storage.abort_multipart_upload(asset.object_key, asset.multipart_upload_id)
                    await storage.delete_object(asset.object_key)
                    if not post_count:
                        await storage.delete_object(asset.thumbnail_key)
                elif asset.storage_path:
                    Path(asset.storage_path).unlink(missing_ok=True)
            except StorageError:
                logger.exception("Could not clean up media asset %s", asset.id)
                continue
            if post_count:
                if asset.storage_backend == "r2":
                    asset.object_key = ""
                    asset.multipart_upload_id = None
                else:
                    asset.storage_path = ""
                asset.status = "expired"
                asset.delete_after = None
            else:
                if asset.storage_backend != "r2" and asset.thumbnail_path:
                    Path(asset.thumbnail_path).unlink(missing_ok=True)
                await db.delete(asset)
        await db.commit()


@celery_app.task(name="marble.cleanup_media")
def cleanup_media() -> None:
    asyncio.run(_cleanup_media())


async def _process_billing_event(event_id: str) -> None:
    from .billing import apply_billing_event

    async with TaskSessionLocal() as db:
        event = await db.get(BillingEvent, event_id)
        if event:
            await apply_billing_event(db, event)


@celery_app.task(
    name="marble.process_billing_event",
    autoretry_for=(OperationalError,),
    retry_backoff=True,
    max_retries=5,
)
def process_billing_event(event_id: str) -> None:
    asyncio.run(_process_billing_event(event_id))


async def _process_pending_billing_events() -> None:
    from .billing import apply_billing_event

    async with TaskSessionLocal() as db:
        events = list(
            await db.scalars(
                select(BillingEvent).where(BillingEvent.processed_at.is_(None)).order_by(BillingEvent.created_at).limit(100)
            )
        )
        for event in events:
            await apply_billing_event(db, event)


@celery_app.task(name="marble.process_pending_billing_events")
def process_pending_billing_events() -> None:
    asyncio.run(_process_pending_billing_events())


async def _sync_analytics(user_id: str, force: bool = False) -> None:
    from .analytics import sync_user_analytics
    from .entitlements import resolve_billing_access

    async with TaskSessionLocal() as db:
        user = await db.get(User, user_id)
        if not user:
            return
        access = await resolve_billing_access(db, user)
        if not access.capabilities["analytics"]:
            return
        await sync_user_analytics(db, user, force=force)
        await publish_realtime_event(user.id, "analytics.updated")


@celery_app.task(
    name="marble.sync_analytics",
    autoretry_for=(OperationalError,),
    retry_backoff=True,
    max_retries=3,
)
def sync_analytics(user_id: str, force: bool = False) -> None:
    asyncio.run(_sync_analytics(user_id, force))


async def _sync_due_analytics() -> None:
    from .entitlements import resolve_billing_access
    from .models import AccountAnalyticsSnapshot, PublicationMetricSnapshot

    async with TaskSessionLocal() as db:
        users = list(await db.scalars(select(User).where(User.email_verified.is_(True))))
        eligible = [user.id for user in users if (await resolve_billing_access(db, user)).capabilities["analytics"]]
        retention_cutoff = utcnow() - timedelta(days=396)
        old_account_snapshots = list(
            await db.scalars(
                select(AccountAnalyticsSnapshot).where(AccountAnalyticsSnapshot.captured_at < retention_cutoff)
            )
        )
        old_publication_snapshots = list(
            await db.scalars(
                select(PublicationMetricSnapshot).where(PublicationMetricSnapshot.captured_at < retention_cutoff)
            )
        )
        for snapshot in [*old_account_snapshots, *old_publication_snapshots]:
            await db.delete(snapshot)
        await db.commit()
    for user_id in eligible:
        sync_analytics.delay(user_id)


@celery_app.task(name="marble.sync_due_analytics")
def sync_due_analytics() -> None:
    asyncio.run(_sync_due_analytics())


async def _run_ai_generation(job_id: str) -> None:
    from .gemini import GeminiClient, GeminiError

    async with TaskSessionLocal() as db:
        job = await db.scalar(select(AIGenerationJob).where(AIGenerationJob.id == job_id))
        if not job or job.status != "queued":
            return
        post = await db.scalar(
            select(Post)
            .where(Post.id == job.post_id)
            .options(selectinload(Post.media), selectinload(Post.versions))
        )
        parent = await db.get(AIGenerationJob, job.parent_job_id) if job.parent_job_id else None
        if not post:
            job.status = "failed"
            job.error_code = "post_not_found"
            job.error_message = "The draft is no longer available"
            job.completed_at = utcnow()
            await db.commit()
            return
        job.status = "processing"
        job.started_at = utcnow()
        await db.commit()
        await publish_realtime_event(job.user_id, "ai.updated", ai_job_id=job.id, post_id=job.post_id)
        client = None
        gemini_file = None
        try:
            client = GeminiClient()
            if job.kind == "adjustment":
                if not parent or not parent.candidate:
                    raise GeminiError("The previous AI suggestion is no longer available")
                candidate, usage = await client.adjust_candidate(
                    parent.candidate,
                    job.adjustment or "regenerate",
                    job.generation_context or "",
                )
            else:
                async with materialize_object(
                    storage_backend=post.media.storage_backend,
                    object_key=post.media.object_key,
                    storage_path=post.media.storage_path,
                    filename=post.media.original_name,
                ) as video_path:
                    gemini_file = await client.upload_file(video_path, post.media.mime_type)
                    candidate, usage = await client.create_candidate(
                        file=gemini_file,
                        current_caption=post.caption,
                        hashtags=post.hashtags or [],
                        platforms=[version.platform for version in post.versions],
                        generation_context=job.generation_context or "",
                    )
            job.candidate = candidate
            job.status = "completed"
            job.input_tokens = usage.get("promptTokenCount")
            job.output_tokens = usage.get("candidatesTokenCount")
        except Exception as exc:
            logger.info("AI generation %s failed: %s", job.id, exc)
            job.status = "failed"
            job.error_code = "ai_generation_failed"
            job.error_message = str(exc)
        finally:
            if client and gemini_file and gemini_file.get("name"):
                try:
                    await client.delete_file(gemini_file["name"])
                except Exception:
                    logger.warning("Could not delete Gemini file for job %s", job.id, exc_info=True)
        job.completed_at = utcnow()
        await db.commit()
        await publish_realtime_event(job.user_id, "ai.updated", ai_job_id=job.id, post_id=job.post_id)


@celery_app.task(
    name="marble.run_ai_generation",
    autoretry_for=(OperationalError,),
    retry_backoff=True,
    max_retries=3,
)
def run_ai_generation(job_id: str) -> None:
    asyncio.run(_run_ai_generation(job_id))


async def _enforce_expired_access() -> None:
    from .email import send_access_expired_email
    from .entitlements import resolve_billing_access

    now = utcnow()
    async with TaskSessionLocal() as db:
        expired_subscriptions = list(
            await db.scalars(
                select(Subscription).where(
                    Subscription.status == "grace",
                    Subscription.grace_until.is_not(None),
                    Subscription.grace_until <= now,
                )
            )
        )
        for subscription in expired_subscriptions:
            subscription.status = "expired"
        scheduled_posts = list(
            await db.scalars(
                select(Post)
                .where(Post.status == "scheduled")
                .options(selectinload(Post.user), selectinload(Post.publications), selectinload(Post.media))
            )
        )
        changed: list[tuple[str, str]] = []
        cancelled_by_user: dict[str, int] = {}
        for post in scheduled_posts:
            access = await resolve_billing_access(db, post.user)
            if access.capabilities["schedule"]:
                continue
            if post.provider_job_id:
                try:
                    await UploadPostClient().cancel_schedule(post.provider_job_id)
                except ProviderError:
                    continue
            post.status = "draft"
            post.publish_mode = None
            post.scheduled_at_utc = None
            post.schedule_timezone = None
            post.provider_job_id = None
            post.provider_request_id = None
            post.media.delete_after = now + timedelta(days=7)
            for publication in list(post.publications):
                await db.delete(publication)
            changed.append((post.user_id, post.id))
            cancelled_by_user[post.user_id] = cancelled_by_user.get(post.user_id, 0) + 1
        await db.commit()
    for user_id, post_id in changed:
        await publish_post_event(user_id, post_id)
    for user_id, count in cancelled_by_user.items():
        async with TaskSessionLocal() as db:
            user = await db.get(User, user_id)
            if user:
                try:
                    await send_access_expired_email(user.email, user.name, count)
                except Exception:
                    logger.warning("Could not deliver access-expiry email to %s", user_id, exc_info=True)


@celery_app.task(name="marble.enforce_expired_access")
def enforce_expired_access() -> None:
    asyncio.run(_enforce_expired_access())
